export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'

export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE'

export const PRODUCT_BY_ID = 'PRODUCT_BY_ID'
export const SET_PRODUCT = 'SET_PRODUCT'
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS'
export const PRODUCT_BY_CAT_ID = 'PRODUCT_BY_CAT_ID'
export const PRODUCT_BY_CAT_ID_SUCCESS = 'PRODUCT_BY_CAT_ID_SUCCESS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY'

export const UPDATE_PRODUCT_PAGINATION = 'UPDATE_PRODUCT_PAGINATION'
export const UPDATE_PRODUCT_PAGINATION_SUCCESS = 'UPDATE_PRODUCT_PAGINATION_SUCCESS'

export const SORT_PRODUCT = 'SORT_PRODUCT'
export const SORT_PRODUCT_SUCCESS = 'SORT_PRODUCT_SUCCESS'

export const CATEGORY_PRODUCT = 'CATEGORY_PRODUCT'
export const CATEGORY_PRODUCT_SUCCESS = 'CATEGORY_PRODUCT_SUCCESS'

export const ALL_CATEGORIES = 'ALL_CATEGORIES'
export const ALL_CATEGORIES_SUCCESS = 'ALL_CATEGORIES_SUCCESS'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
